#!/bin/bash

export KUBE_CONFIG_DIR="$HOME/.kube"
export KUBE_JOIN_PARAM=""
export KUBE_POD_CIDR="192.168.0.0/16"
export KUBE_SVC_CIDR="10.96.0.0/16"
export KUBE_NET_CONF="https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml"
export APP_NAME="k8s"
export NODE_IP="172.16.100.20"
export NODE_MASK="255.255.255.0"
export NODE_DOM="kmaster.com"
export NODE_NAME="kmaster"
export PROXY_ENABLED="true"

export http_proxy=""
export https_proxy=""
export no_proxy=""
export HTTP_PROXY=""
export HTTPS_PROXY=""
export NO_PROXY=""

[[ $PROXY_ENABLED == "true" ]] && . setProxy
